name = "GadgetSearcher"
uuid = "d80eeeda-0322-46b6-834d-ddfe12300d12"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GenericTensorNetworks = "3521c873-ad32-4bb4-b63d-f4f178f42b49"
GraphIO = "aa1b3936-2fda-51b9-ab35-c553d3a640a2"

[compat]
DocStringExtensions = "0.9"
GenericTensorNetworks = "1"
GraphIO = "0.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
